// swift-tools-version: 5.10
// This Package.swift is only used to resolve SPM dependencies.
// The actual Xcode project is generated by XcodeGen (project.yml).
// Run: xcodegen generate

import PackageDescription

let package = Package(
    name: "ClubOSDeps",
    platforms: [.iOS(.v16)],
    dependencies: [
        .package(url: "https://github.com/supabase/supabase-swift", from: "2.0.0"),
    ],
    targets: [
        .target(name: "ClubOSDeps", dependencies: [
            .product(name: "Supabase", package: "supabase-swift"),
        ]),
    ]
)
