#!/bin/bash
set -euo pipefail

# ============================================
# ClubOS — Staging Environment Setup
# ============================================
# Run this once to create a Supabase staging project,
# apply migrations, seed data, and configure Vercel.
#
# Prerequisites:
#   - supabase CLI installed (brew install supabase/tap/supabase)
#   - Vercel CLI installed (npm i -g vercel)
#   - Logged into both: `supabase login` + `vercel login`
#
# Usage:
#   chmod +x scripts/setup-staging.sh
#   ./scripts/setup-staging.sh

echo "╔══════════════════════════════════════════╗"
echo "║   ClubOS — Staging Environment Setup     ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Create Supabase staging project ──────
echo "── Step 1: Supabase Staging Project ──"
echo ""
echo "Option A (recommended): Create via Supabase dashboard"
echo "  1. Go to https://supabase.com/dashboard"
echo "  2. Click 'New Project'"
echo "  3. Name it: clubos-staging"
echo "  4. Region: us-east-1 (same as prod)"
echo "  5. Generate a strong DB password"
echo "  6. Copy the project URL and keys"
echo ""
echo "Option B: Use Supabase CLI branching (requires Pro plan)"
echo "  supabase branches create staging --project-ref iicwnlruopqhrzkgjsmu"
echo ""

read -p "Enter your staging Supabase project ref (e.g. abcdefghijklmnop): " STAGING_REF

if [ -z "$STAGING_REF" ]; then
  echo "Error: Project ref required. Create the project first."
  exit 1
fi

STAGING_URL="https://${STAGING_REF}.supabase.co"
echo ""
echo "Staging URL: $STAGING_URL"

# ── 2. Link and apply migrations ────────────
echo ""
echo "── Step 2: Apply Migrations ──"
echo ""
echo "Linking to staging project..."
supabase link --project-ref "$STAGING_REF"

echo "Pushing all migrations to staging..."
supabase db push

echo "Seeding staging database..."
supabase db reset --linked

echo "✓ Migrations applied and data seeded"

# ── 3. Get API keys ─────────────────────────
echo ""
echo "── Step 3: Retrieve Keys ──"
echo ""
echo "Fetching API keys for staging project..."

ANON_KEY=$(supabase status --output json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('anon_key',''))" 2>/dev/null || echo "")
SERVICE_KEY=$(supabase status --output json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('service_role_key',''))" 2>/dev/null || echo "")

if [ -z "$ANON_KEY" ]; then
  echo "Could not auto-detect keys. Get them from:"
  echo "  https://supabase.com/dashboard/project/${STAGING_REF}/settings/api"
  echo ""
  read -p "Enter anon key: " ANON_KEY
  read -p "Enter service role key: " SERVICE_KEY
fi

# ── 4. Create .env.staging.local ─────────────
echo ""
echo "── Step 4: Create .env.staging.local ──"
cat > apps/web/.env.staging.local <<EOF
# ClubOS Staging Environment
# Auto-generated by scripts/setup-staging.sh

NEXT_PUBLIC_SUPABASE_URL=${STAGING_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}

# Stripe — use TEST mode keys (same as dev)
STRIPE_SECRET_KEY=\${STRIPE_SECRET_KEY}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=\${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=\${STRIPE_WEBHOOK_SECRET}

# AI + Email — shared across envs
ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
RESEND_API_KEY=\${RESEND_API_KEY}

# Staging identity
NEXT_PUBLIC_ENV=staging
NEXT_PUBLIC_APP_URL=https://clubos-staging.vercel.app
EOF

echo "✓ Created apps/web/.env.staging.local"

# ── 5. Configure Vercel ──────────────────────
echo ""
echo "── Step 5: Vercel Staging Branch ──"
echo ""
echo "You need to set up Vercel environment variables for the 'staging' branch."
echo "Go to: https://vercel.com → Project Settings → Environment Variables"
echo ""
echo "Add these with 'Preview' scope, filtered to branch 'staging':"
echo ""
echo "  NEXT_PUBLIC_SUPABASE_URL = ${STAGING_URL}"
echo "  NEXT_PUBLIC_SUPABASE_ANON_KEY = ${ANON_KEY}"
echo "  SUPABASE_SERVICE_ROLE_KEY = ${SERVICE_KEY}"
echo "  NEXT_PUBLIC_ENV = staging"
echo "  NEXT_PUBLIC_APP_URL = (your staging Vercel URL)"
echo ""
echo "Stripe, Anthropic, and Resend keys can be shared with production"
echo "or use separate test keys."

# ── 6. Create staging branch ─────────────────
echo ""
echo "── Step 6: Git Branch ──"

if git show-ref --verify --quiet refs/heads/staging 2>/dev/null; then
  echo "✓ 'staging' branch already exists"
else
  echo "Creating 'staging' branch from main..."
  git branch staging main
  echo "✓ Created 'staging' branch"
fi

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║            Setup Complete!               ║"
echo "╠══════════════════════════════════════════╣"
echo "║                                          ║"
echo "║  Workflow:                               ║"
echo "║    main     → prod (auto-deploy)         ║"
echo "║    staging  → staging (auto-deploy)      ║"
echo "║    feature/* → PR previews               ║"
echo "║                                          ║"
echo "║  Deploy to staging:                      ║"
echo "║    git checkout staging                  ║"
echo "║    git merge main                        ║"
echo "║    git push origin staging               ║"
echo "║                                          ║"
echo "║  Promote staging → prod:                 ║"
echo "║    git checkout main                     ║"
echo "║    git merge staging                     ║"
echo "║    git push origin main                  ║"
echo "║                                          ║"
echo "╚══════════════════════════════════════════╝"
